// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VigoCarCompany.Data;

namespace VigoCarCompany.Migrations
{
    [DbContext(typeof(VigoDbContext))]
    partial class VigoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VigoCarCompany.Models.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Make1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Make2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Make3"
                        });
                });

            modelBuilder.Entity("VigoCarCompany.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MakeId = 1,
                            Name = "Model1 Make1"
                        },
                        new
                        {
                            Id = 2,
                            MakeId = 1,
                            Name = "Model2 Make1"
                        },
                        new
                        {
                            Id = 3,
                            MakeId = 1,
                            Name = "Model3 Make1"
                        },
                        new
                        {
                            Id = 4,
                            MakeId = 2,
                            Name = "Model4 Make2"
                        },
                        new
                        {
                            Id = 5,
                            MakeId = 2,
                            Name = "Model5 Make2"
                        },
                        new
                        {
                            Id = 6,
                            MakeId = 2,
                            Name = "Model6 Make2"
                        },
                        new
                        {
                            Id = 7,
                            MakeId = 3,
                            Name = "Model7 Make3"
                        },
                        new
                        {
                            Id = 8,
                            MakeId = 3,
                            Name = "Model8 Make3"
                        },
                        new
                        {
                            Id = 9,
                            MakeId = 3,
                            Name = "Model9 Make3"
                        });
                });

            modelBuilder.Entity("VigoCarCompany.Models.Model", b =>
                {
                    b.HasOne("VigoCarCompany.Models.Make", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("VigoCarCompany.Models.Make", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
